name: app_capachica
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  get_storage: ^2.1.1
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  intl: ^0.20.2
  google_sign_in: ^6.3.0
  webview_flutter: ^4.7.0
  font_awesome_flutter: ^10.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/logo.png # Tu logo aquí
    - assets/background_home.jpg # Nueva imagen de fondo
    - assets/google_logo.png # Logo de Google

  uses-material-design: true